name: cyber_ssl_anomaly_det_test
entrypoint: >-
  python -m determined.launch.torch_distributed
  python determined/coreapi_train.py

hyperparameters:
  batch_size: 4
  multi: True
  epochs: -1
  dist: True
  ssl_train: True

max_restarts: 0
resources:
  slots_per_trial: 16

searcher:
  name: single
  metric: avg_val_acc
  max_length: 33
  smaller_is_better: False

